support for ArrayField, fix of TypeError: unhashable type: 'list'
jazzband/django-auditlog pull request #181
Opened 2018-08-02 12:57 UTC by eriktelepovsky

2018-09-17 18:34 UTC, audiolion commented
Hi @eriktelepovsky thanks for the PR, could you include a test for this change? Thanks 👍

2022-10-13 09:58 UTC, alieh-rymasheuski requested changes

2022-10-13 09:58 UTC, alieh-rymasheuski commented on auditlog/migrations/0004_logentry_detailed_object_repr.py
> +    # Django 3.1
I don't think we officially support Django pre-3.2.

2022-10-13 09:58 UTC, alieh-rymasheuski commented on auditlog/models.py
> +                        if isinstance(value, list):
Can we move this `isinstance` check to line 455 (where we test `if type(value) is list` rather than `if isinstance(value, list)`?

2022-10-13 09:58 UTC, alieh-rymasheuski commented on auditlog/settings.py
> +ENABLE_ELLIPSIS = getattr(settings, "AUDITLOG_ENABLE_ELLIPSIS", True)
Should this change be a part of this pull request?

2022-10-13 10:00 UTC, alieh-rymasheuski commented
I wonder why this pull request appeared in my Github inbox. Apparently, it was because of an unrelated push to `eriktelepovsky:master`.

2022-12-17 20:43 UTC, aqeelat commented
@hramezani I really don't understand the changes in this PR. It solves nothing. I think this PR should be closed.

2022-12-20 11:11 UTC, hramezani commented
Going to close it because it is too old

2022-12-20 11:11 UTC, closed without merging