Support Django's save method `update_fields` kwarg
jazzband/django-auditlog pull request #336
Opened 2021-12-15 18:39 UTC by AbdullahKady

Solves #243 

This has been an irritating issue that I've been facing, the [issue](https://github.com/jazzband/django-auditlog/issues/243) seems to describe it quite well.
Please let me know if you have any comments :)

2022-01-06 15:11 UTC, AbdullahKady commented
@hramezani @Linkid can I get an update regarding this please? I cannot request a review on the PR.
Just in case if there is anything blocking from my side, or if there is a decision that this bug is not relevant.

2022-01-06 15:46 UTC, hramezani commented
Let's wait for @Linkid pr https://github.com/jazzband/django-auditlog/pull/339 and then the CI will be green.

@Linkid Could you please take a look meanwhile?

2022-01-07 08:55 UTC, Linkid requested changes
Nice ! Some minor changes to do and it will be great ! Thank you.

2022-01-07 08:55 UTC, Linkid commented on auditlog_tests/tests.py
> +        the package should too. https://docs.djangoproject.com/en/models/instances/#specifying-which-fields-to-save
The link is not working. You can use this one instead: https://docs.djangoproject.com/en/3.2/ref/models/instances/#specifying-which-fields-to-save (3.2 is the latest LTS).

2022-01-07 08:55 UTC, Linkid commented on auditlog_tests/tests.py
> +        # Passing `None`` should save both fields according to Django.
Typo: ``` `None`` ``` → `None`

2022-01-07 12:38 UTC, Linkid approved these changes
LGTM

2022-01-07 13:23 UTC, hramezani approved these changes
Thanks @AbdullahKady

2022-01-07 13:23 UTC, merged